/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameCompte;

import gestion.synchro.ThreadCompteDepot;
import gestion.synchro.ThreadCompteRetrait;
import gestion.transaction.Compte;
import java.awt.GraphicsConfiguration;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author NIASS
 */
public class AccueilBanque extends JFrame {
    /**
     * Creates new form AccueilBanque
     */
    private Connection con;
    PreparedStatement st;
    private static boolean compteIsLoaded = false;
    private ThreadCompteRetrait threadRetrait;
    private ThreadCompteDepot threadDepot;
    private Compte client;
    public AccueilBanque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prnom = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        historique = new javax.swing.JButton();
        nom1 = new javax.swing.JTextField();
        decouvert1 = new javax.swing.JTextField();
        numcompte = new javax.swing.JTextField();
        solde1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        depot = new javax.swing.JButton();
        retrait = new javax.swing.JButton();
        montantretrait = new javax.swing.JTextField();
        numcompte2 = new javax.swing.JTextField();
        montdepot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ouverture Compte Personnel"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Prenom");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Solde");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Decouvert");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("NumerCompte");

        prnom.setBackground(new java.awt.Color(108, 122, 137));
        prnom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prnomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prnomMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prnomMouseReleased(evt);
            }
        });
        prnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prnomActionPerformed(evt);
            }
        });

        create.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        create.setText("Creer Compte");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createMouseEntered(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        historique.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        historique.setText("Historique");
        historique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historiqueMouseEntered(evt);
            }
        });
        historique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiqueActionPerformed(evt);
            }
        });

        nom1.setBackground(new java.awt.Color(108, 122, 137));
        nom1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nom1MouseEntered(evt);
            }
        });
        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });

        decouvert1.setBackground(new java.awt.Color(108, 122, 137));
        decouvert1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        decouvert1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decouvert1MouseEntered(evt);
            }
        });
        decouvert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decouvert1ActionPerformed(evt);
            }
        });

        numcompte.setBackground(new java.awt.Color(108, 122, 137));
        numcompte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numcompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numcompteMouseEntered(evt);
            }
        });
        numcompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcompteActionPerformed(evt);
            }
        });

        solde1.setBackground(new java.awt.Color(108, 122, 137));
        solde1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solde1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solde1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solde1MouseEntered(evt);
            }
        });
        solde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solde1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(historique))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numcompte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decouvert1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prnom, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nom1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(solde1)))))
                .addGap(161, 161, 161))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prnom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solde1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decouvert1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numcompte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(historique))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textArea.setBackground(new java.awt.Color(0, 153, 153));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opération sur le solde"));
        jPanel6.setForeground(new java.awt.Color(255, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Numéro Compte");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Montant Retrait");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Montant Depôt");

        depot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        depot.setText("Depôt");
        depot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depotActionPerformed(evt);
            }
        });

        retrait.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        retrait.setText("Retrait");
        retrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retraitMouseClicked(evt);
            }
        });
        retrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrait(evt);
            }
        });

        montantretrait.setBackground(new java.awt.Color(108, 122, 137));
        montantretrait.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        montantretrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                montantretraitMouseEntered(evt);
            }
        });
        montantretrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantretraitActionPerformed(evt);
            }
        });

        numcompte2.setBackground(new java.awt.Color(108, 122, 137));
        numcompte2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        numcompte2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numcompte2MouseEntered(evt);
            }
        });
        numcompte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcompte2ActionPerformed(evt);
            }
        });

        montdepot.setBackground(new java.awt.Color(108, 122, 137));
        montdepot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        montdepot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                montdepotMouseEntered(evt);
            }
        });
        montdepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montdepotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(depot, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(retrait, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(montantretrait, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(numcompte2)
                    .addComponent(montdepot, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numcompte2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(montantretrait, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(montdepot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retrait)
                    .addComponent(depot)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void prnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prnomActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_prnomActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
         con=Myconnection.getConnection();
         if(prnom.getText().isEmpty() || nom1.getText().isEmpty()||decouvert1.getText().isEmpty()||numcompte.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"Tous les champs doivent être remplis", "ERROR", 3, null);
         }else{
            String prenom = prnom.getText();
            String nom=nom1.getText();
            double solde=Double.parseDouble(solde1.getText());
            double decouvert=Double.parseDouble(decouvert1.getText());
            int numerocompte=Integer.parseInt(numcompte.getText());
            Compte Newcmpo=new Compte(nom, prenom, solde, decouvert, numerocompte);
            try {
                st=con.prepareStatement("INSERT INTO `client`(`prenom`, `nom`, `solde`, `decouvert`, `numerocompte`) VALUES (?,?,?,?,?)");
                st.setString(1,Newcmpo.getPrenom() );
                st.setString(2,Newcmpo.getNom());
                st.setDouble(3, Newcmpo.getSolde());
                st.setDouble(4, Newcmpo.getDecouvert());
                st.setInt(5, Newcmpo.getNumeroCompte());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Compte crée");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"ERREUR LORS DE LA CREATION DED COMPTE");
            }
         }
    }//GEN-LAST:event_createActionPerformed
        private Compte NewCompt2;
    private void historiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiqueActionPerformed
         //historique
        if(!numcompte.getText().isEmpty()){
        try {
      con=Myconnection.getConnection();
      int NumCompte=Integer.parseInt(numcompte.getText());
      st=con.prepareStatement("SELECT * FROM `client` WHERE numerocompte = ?");
      st.setInt(1, NumCompte);
      ResultSet resultat=st.executeQuery();
      if(!resultat.wasNull()){
      while(resultat.next()){
      this.NewCompt2=new Compte(resultat.getString("prenom"),resultat.getString("nom"),
      resultat.getDouble("solde"), resultat.getDouble("decouvert"), resultat.getInt("numerocompte"));               
    }
      }else {             
                }
}catch (SQLException ex) {
ex.printStackTrace();
Logger.getLogger(AccueilBanque.class.getName()).log(Level.SEVERE, null, ex);
        }
try {
   textArea.setText(this.NewCompt2.getHistorique());
   }catch(NullPointerException e2) {
    JOptionPane.showMessageDialog(null,
  "Erreur,Ce numéro de compte n'existe pas! ",
  "Compte introuvable", 0, null);
    }      
   }//end of first if
        else {
    JOptionPane.showMessageDialog(null,
    "Pour voir les details sur votre compte, tu dois remplir le champ du numero de compte");
        }
    }//GEN-LAST:event_historiqueActionPerformed

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createMouseClicked

    private void depotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depotActionPerformed
        //depot
        if(numcompte2.getText().isEmpty()){
       JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas entre un numéro de compte",
        "Ce champs ne doit pas etre vide", 0, null);
        }
      if(montdepot.getText().isEmpty()){
JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas entre une valeur pour le depot",
"Ce champs ne doit pas etre vide", 0, null);
      }
      if(!numcompte2.getText().isEmpty() && !montdepot.getText().isEmpty()){
          con=Myconnection.getConnection();
          // Compte clientDepot = null;
          int numeromcompte=Integer.parseInt(numcompte2.getText());
          double montantdepot=Integer.parseInt(montdepot.getText());
          try {
         st=con.prepareStatement("SELECT * FROM `client` WHERE numerocompte = ?");
         st.setInt(1, numeromcompte);
         ResultSet resultat=st.executeQuery();
         if(resultat.next()){
         if(!compteIsLoaded){
         client = new Compte(resultat.getString("prenom"), resultat.getString("nom"),
         resultat.getDouble("solde"), resultat.getDouble("decouvert"), resultat.getInt("numerocompte"));
         compteIsLoaded = true;
         } else {
         compteIsLoaded = false;
	}
       }
         else{
             JOptionPane.showMessageDialog(null, "Erreur,ce numéro de compte n'est pas bon", null, 0,null);
         }       
          } catch (SQLException e) {
            e.printStackTrace();
        JOptionPane.showMessageDialog(null, "1111111111111111111111111111", null, 0,null);
          }
            if (threadRetrait != null && threadRetrait.isAlive()) {
	JOptionPane.showMessageDialog(null, "Une operation de retrait est en cours d'execution ..",
	"Veuillez patienter ...", 0, null);
        }
        if (client != null) {
	threadDepot = new ThreadCompteDepot("DepotThread", client, montantdepot,numeromcompte );
	threadDepot.start();			}    
      }
    }//GEN-LAST:event_depotActionPerformed

    private void retrait(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrait
        //retrait
       if(numcompte2.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas entre un numéro de compte",
        "le champs ne doit pas etre vide!", 0, null);
       }
      if(montantretrait.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Erreur, vous n'avez pas entre une valuer pour le retrait",
            "le champs ne doit pas etre vide", 0, null);
      }
      if(!numcompte2.getText().isEmpty() && !montantretrait.getText().isEmpty()){
          con=Myconnection.getConnection();
          int numeroCompte = Integer.parseInt(numcompte2.getText());
          int montantAretrait=Integer.parseInt(montantretrait.getText());
          try {
              st=con.prepareStatement("SELECT * FROM `client` WHERE `numerocompte`= ?");
              st.setInt(1,numeroCompte);
              ResultSet resultat=st.executeQuery();
              if(resultat.next()){
                if(!compteIsLoaded){
                client=new Compte(resultat.getString("prenom"), resultat.getString("nom"),resultat.getDouble("solde"),
                        resultat.getDouble("decouvert"), resultat.getInt("numerocompte"));
                compteIsLoaded = true;
                  }else {
                compteIsLoaded = false;
                }
              }else {
             JOptionPane.showMessageDialog(null, "Erreur,ce numéro de compte n'est pas bon", null, 0,null);
           }
          } catch (SQLException e) {
              e.printStackTrace();
          }
            if (threadDepot != null && threadDepot.isAlive()) {
             JOptionPane.showMessageDialog(null, "Une operation de depot est en cours d'execution ..",
                "Veuillez patienter ...", 0, null);
            }
          if(client!=null){
          threadRetrait=new ThreadCompteRetrait("RetraitThread", client, montantAretrait,numeroCompte);
          threadRetrait.start();
      }
      }
     
    }//GEN-LAST:event_retrait

    private void retraitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retraitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_retraitMouseClicked

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1ActionPerformed

    private void decouvert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decouvert1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decouvert1ActionPerformed

    private void numcompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcompteActionPerformed

    private void solde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solde1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solde1ActionPerformed

    private void montantretraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantretraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantretraitActionPerformed

    private void numcompte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcompte2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcompte2ActionPerformed

    private void montdepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montdepotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montdepotActionPerformed

    private void prnomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prnomMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_prnomMouseReleased

    private void prnomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prnomMouseEntered
        ((AbstractDocument) prnom.getDocument()).setDocumentFilter(new FilterString());
    }//GEN-LAST:event_prnomMouseEntered

    private void nom1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom1MouseEntered
        // TODO add your handling code here:
        ((AbstractDocument) nom1.getDocument()).setDocumentFilter(new FilterString());
    }//GEN-LAST:event_nom1MouseEntered

    private void solde1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solde1MouseClicked
         // TODO add your handling code here:

    }//GEN-LAST:event_solde1MouseClicked

    private void numcompteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numcompteMouseEntered
        // TODO add your handling code here:
        ((AbstractDocument) numcompte.getDocument()).setDocumentFilter(new FilterdixChiffre());
    }//GEN-LAST:event_numcompteMouseEntered

    private void solde1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solde1MouseEntered
        // TODO add your handling code here:
        ((AbstractDocument) solde1.getDocument()).setDocumentFilter(new FilterNumber(solde1));
    }//GEN-LAST:event_solde1MouseEntered

    private void decouvert1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decouvert1MouseEntered
        // TODO add your handling code here:
        ((AbstractDocument) decouvert1.getDocument()).setDocumentFilter(new FilterNumber(decouvert1));
    }//GEN-LAST:event_decouvert1MouseEntered

    private void prnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prnomMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_prnomMouseClicked

    private void historiqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historiqueMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_historiqueMouseEntered

    private void createMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_createMouseEntered

    private void numcompte2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numcompte2MouseEntered
        // TODO add your handling code here:
        ((AbstractDocument) numcompte2.getDocument()).setDocumentFilter(new FilterdixChiffre());
    }//GEN-LAST:event_numcompte2MouseEntered

    private void montantretraitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montantretraitMouseEntered
        // TODO add your handling code here:
      ((AbstractDocument) montantretrait.getDocument()).setDocumentFilter(new FilterNumber(montantretrait));
    }//GEN-LAST:event_montantretraitMouseEntered

    private void montdepotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montdepotMouseEntered
        // TODO add your handling code here:
     ((AbstractDocument) montdepot.getDocument()).setDocumentFilter(new FilterNumber(montdepot));
    }//GEN-LAST:event_montdepotMouseEntered

    public AccueilBanque(GraphicsConfiguration gc) {
        super(gc);
    }

 ////// trois class interne pour filtrer les donnes de l'utilisateur///////
	class AlphabetFilter extends DocumentFilter {
		@SuppressWarnings("deprecation")
		@Override
		public void replace(DocumentFilter.FilterBypass fb, int i, int i1, String string, AttributeSet as)
				throws BadLocationException {
			for (int n = string.length(); n > 0; n--) {

				char c = string.charAt(n - 1);// get a single character of the
												// string
				// tenir compte de l'espace pour certains noms ou prenom
				if (Character.isAlphabetic(c) || Character.isSpace(c)) {
					// if its an alphabetic character
					super.replace(fb, i, i1, String.valueOf(c), as);
				}
			}
		}
		@Override
		public void remove(DocumentFilter.FilterBypass fb, int i, int i1) throws BadLocationException {
			super.remove(fb, i, i1);
		}

		@Override
		public void insertString(DocumentFilter.FilterBypass fb, int i, String string, AttributeSet as) throws BadLocationException {
			super.insertString(fb, i, string, as);

		}
	}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JTextField decouvert1;
    private javax.swing.JButton depot;
    private javax.swing.JButton historique;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField montantretrait;
    private javax.swing.JTextField montdepot;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField numcompte;
    private javax.swing.JTextField numcompte2;
    private javax.swing.JTextField prnom;
    private javax.swing.JButton retrait;
    private javax.swing.JTextField solde1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
